{% set name = "tsdownsample" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tsdownsample-{{ version }}.tar.gz
  sha256: 5268d0ab5e8572138871feff389440a0c59d5e0fe02c0fa1cf975d74ba33b933

build:
  skip: true  # [py<37 or win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - python                                   # [build_platform != target_platform]
    - cross-python_{{ target_platform }}       # [build_platform != target_platform]
    - crossenv                                 # [build_platform != target_platform]
    - maturin >=1.1,<2.0                       # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
  host:
    - python
    - maturin >=0.14,<0.15
    - pip
  run:
    - python
    - numpy


test:
  imports:
    - tsdownsample
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/predict-idlab/tsdownsample
  summary: Time series downsampling in Rust
  license: MIT
  license_file:
    - LICENSE
    - downsample_rs/LICENSE

extra:
  recipe-maintainers:
    - thewchan
