{% set name = "tsdownsample" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tsdownsample-{{ version }}.tar.gz
  sha256: 9da0b8f8859e9651910cc150bc5115bf5d1890d8ebee12bf57bd1bb016a0112a

build:
  skip: True  # [py<37 or win]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
      - {{ compiler('c') }}
      - {{ compiler('rust') }}
  host:
    - python
    - maturin >=0.14,<0.15
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - tsdownsample
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/predict-idlab/tsdownsample
  summary: Time series downsampling in Rust
  license: MIT
  license_file:
    - LICENSE
    - local_dependencies/downsample_rs/LICENSE

extra:
  recipe-maintainers:
    - thewchan
